---
app_options:
    php: true
    php_version: '7.3'

app_patterns:
    timezone_default: UTC

    php_extensions:
        # Symfony
        - intl
        - curl
        - mbstring
        - xml
        # App

    php_configs:
        - file: app_opcache.ini
          template: configs/app_opcache.{{ env }}.j2
        - file: app.ini
          template: configs/app.{{ env }}.j2
          config:
              - date.timezone: UTC

    nginx_configs:
        # Php fpm
        - file: app_php_fpm
          template: configs/app_php_fpm.{{ env }}.j2
        # Gzip
        - file: app_gzip
          template: configs/app_gzip.{{ env }}.j2
        # App
        - file: app.conf
          config:
              - server:
                    - listen: 80
                    - listen: 8000
                    - listen: 8001
                    - server_name: '{{ app.host }}'
                    #- server_name: "*.ngrok.io"
                    - root: '{{ app.dir }}{{ app.dir_release }}/tests/Bridge/Symfony/Application/public'
                    - access_log: '{{ app.log_dir }}/nginx.access.log'
                    - error_log: '{{ app.log_dir }}/nginx.error.log'
                    - include: conf.d/app_gzip
                    - location /:
                          - try_files: $uri /index.php$is_args$args
                    - location ~ ^/index\.php(/|$):
                          - include: conf.d/app_php_fpm
                          - set: $APP_ENV dev
                          - if ( $server_port = 8000 ):
                                - set: $APP_ENV test
                          - if ( $server_port = 8001 ):
                                - set: $APP_ENV prod
                          - fastcgi_param: APP_ENV $APP_ENV
                          - internal;

    # files_attributes:
    #     - path: '{{ app.dir }}{{ app.dir_release }}/tests/Bridge/Symfony/Application/var/log'
    #       src: '{{ app.log_dir }}'
    #       state: link_directory
    #     - path: '{{ app.dir }}{{ app.dir_release }}/tests/Bridge/Symfony/Application/var/cache'
    #       src: '{{ app.cache_dir }}'
    #       state: link_directory
