symfony_mailer_testing_reset:
    path: /_symfony_mailer_testing/reset
    controller: Yproximite\SymfonyMailerTesting\Controller\MailerController::reset
    methods: POST

symfony_mailer_testing_message_events_get:
    path: /_symfony_mailer_testing/events
    controller: Yproximite\SymfonyMailerTesting\Controller\MailerController::getEvents
    methods: GET
