services:
    _defaults:
        autowire: true
        autoconfigure: true

    Yproximite\SymfonyMailerTesting\MailerLogger: ~

    Yproximite\SymfonyMailerTesting\Test\MailerAssertions: ~

    Yproximite\SymfonyMailerTesting\Bridge\Symfony\EventListener\MailerLoggerListener: ~

    # Behat
    Yproximite\SymfonyMailerTesting\Bridge\Behat\MailerContext: ~
