services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        Yproximite\SymfonyMailerTesting\MailerLoggerAwareInterface:
            calls:
                - [setMailerLogger, ['@Yproximite\SymfonyMailerTesting\MailerLogger']]

    Yproximite\SymfonyMailerTesting\MailerLogger: ~

    Yproximite\SymfonyMailerTesting\Normalizer\:
        resource: '../../../../Normalizer/*'

    Yproximite\SymfonyMailerTesting\Bridge\Symfony\EventListener\MailerLoggerListener: ~

    # Behat
    Yproximite\SymfonyMailerTesting\Bridge\Behat\MailerContext: ~
