name: CI

on:
    push:
        branches:
            - main
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]

env:
    PHPUNIT_FLAGS: -v
    COMPOSER_MEMORY_LIMIT: -1

    PHP_VERSION_DEFAULT: 7.3
    NODE_VERSION: 14.x

jobs:
    static_analysis:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ env.PHP_VERSION_DEFAULT }}
                  ini-values: memory_limit=-1, session.gc_probability=0, opcache.enable=1, opcache.enable_cli=1, opcache.memory_consumption=256, opcache.max_accelerated_files=20000, opcache.validate_timestamps=0, realpath_cache_size=4096K, realpath_cache_ttl=600

            - name: Install Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ env.NODE_VERSION }}

            - run: composer install --prefer-dist --no-interaction --no-progress
            - run: cp .github/psr_http_message_bridge.yaml fixtures/applications/Symfony/config/packages
            - run: cp .github/nyholm_psr7.yaml fixtures/applications/Symfony/config/packages
            - run: composer require symfony/psr7-pack # To make PHPStan and me happy, it prevent me to write stubs for PHPStan

            - run: composer validate --strict

            - run: composer phpstan

            - run: composer php-cs-fixer@ci

            - run: yarn install --frozen-lockfile

            - run: yarn lint

    test:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                config:
                    # Minimum supported dependencies with the latest and oldest PHP version
                    - PHP_VERSION: 7.3
                      COMPOSER_FLAGS: --prefer-stable --prefer-lowest

                    # Test the latest stable release
                    - PHP_VERSION: 7.3
                    - PHP_VERSION: 7.4
                    - PHP_VERSION: 8.0
                      COVERAGE: true
                      PHPUNIT_FLAGS: -v --coverage-text

                    # Test specific Symfony versions
                    - PHP_VERSION: 7.4
                      SYMFONY_VERSION: 4.4.* # Last 4.x version
                    - PHP_VERSION: 7.4
                      SYMFONY_VERSION: 5.* # Last 5.x version
                    - PHP_VERSION: 8.0
                      SYMFONY_VERSION: 4.4.* # Last 4.x version
                    - PHP_VERSION: 8.0
                      SYMFONY_VERSION: 5.* # Last 5.x version

                    # Latest commit to master (disabled until GitHub Actions support allowed_failures)
                    # - PHP_VERSION: 7.4
                    #   STABILITY: dev
                    #   ALLOWED_TO_FAIL: true

        steps:
            - uses: actions/checkout@v2

            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.config.PHP_VERSION }}
                  coverage: ${{ matrix.config.COVERAGE }}
                  ini-values: memory_limit=-1, session.gc_probability=0, opcache.enable=1, opcache.enable_cli=1, opcache.memory_consumption=256, opcache.max_accelerated_files=20000, opcache.validate_timestamps=0, realpath_cache_size=4096K, realpath_cache_ttl=600

            - name: Install globally Symfony Flex
              run: composer global require --no-progress --no-scripts --no-plugins symfony/flex dev-main

            - name: Configure Composer minimum stability
              if: matrix.config.STABILITY
              run: composer config minimum-stability ${{ matrix.config.STABILITY }}

            - name: Limit to specific Symfony version
              if: matrix.config.SYMFONY_VERSION
              run: echo "SYMFONY_REQUIRE=${{ matrix.config.SYMFONY_VERSION }}" >> $GITHUB_ENV

            - name: Install composer dependencies
              run: composer update ${{ matrix.config.COMPOSER_FLAGS }} --prefer-dist --no-interaction --no-progress

            - name: Run PHPUnit
              run: composer phpunit -- ${{ matrix.config.PHPUNIT_FLAGS }}

            - name: Run phpspec
              run: composer phpspec run

            - name: Run Behat
              run: composer behat

    cypress:
        runs-on: ubuntu-latest
        name: cypress
        steps:
            - uses: actions/checkout@v2

            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ env.PHP_VERSION_DEFAULT }}
                  coverage: none
                  extensions: ctype, iconv, intl
                  ini-values: memory_limit=-1, session.gc_probability=0, opcache.enable=1, opcache.enable_cli=1, opcache.memory_consumption=256, opcache.max_accelerated_files=20000, opcache.validate_timestamps=0, realpath_cache_size=4096K, realpath_cache_ttl=600

            - name: Install Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ env.NODE_VERSION }}

            - run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
            - run: cp .github/psr_http_message_bridge.yaml fixtures/applications/Symfony/config/packages
            - run: cp .github/nyholm_psr7.yaml fixtures/applications/Symfony/config/packages
            - run: composer require symfony/psr7-pack

            - run: composer server-start

            - name: Run Cypress
              uses: cypress-io/github-action@v2

            - run: composer server-stop
